import { getNavigationTree } from "@/lib/autoNav";
import ClientLayout from "./client-layout";
import { Geist, Geist_Mono } from "next/font/google";

export const metadata = {
  title: "Vipassana Research Institute",
  description: "Test",
  // favicon:  "\vecel.svg"
};
 const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  const menuData = getNavigationTree();

  return (
    <html lang="en">
      <body >
        <ClientLayout menuData={menuData}>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}

// import "./globals.css";
// import { Geist, Geist_Mono } from "next/font/google";
// import ThemeRegistry from "./themeregistry";
// import Header from "./components/Header";
// import { Box } from "@mui/material";
// import { red } from "@mui/material/colors";
// import PermanentDrawerWithTree from "./components/gemini";
// // import { getNavigationTree } from "@/lib/navigation";
// import { getNavigationTree } from "@/lib/autoNav";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   // const menuData = getNavigationTree();
//   const menuData = getNavigationTree();
//   console.log(
//     "--- NAVIGATION TREE DATA ---",
//     JSON.stringify(menuData, null, 2)
//   );
//   return (
//     <html lang="en">
//       <body>
//         {/* className={`${geistSans.variable} ${geistMono.variable}`} */}
//         <ThemeRegistry>
//           <Box sx={{ display: "flex", gap: "1vw", position: "absolute" }}>
//             {/* <PermanentDrawer /> */}
//             <PermanentDrawerWithTree menuData={menuData} />
//             <Box
//               sx={{
//                 flexGrow: 1,
//                 width: "92vw",

//                 // backgroundColor: red[400],
//               }}
//             >
//               <Header />
//               {children}
//             </Box>
//           </Box>
//         </ThemeRegistry>
//       </body>
//     </html>
//   );
// }
